"""Generate job.dag for the simulated-case control/dirty/prediction PE sweep.

Sweeps every event in pe_cases_n10.pkl (generated by evaluate_pe_cases.py)
against the three injection types run.py understands, except events whose
chirp mass falls outside run.py's hardcoded prior range (10-100 Msun) --
those hit an immediate exit() in setup_priors. Run from anywhere; it only
writes scripts/pe/condor/job.dag by default; pass --events/--out for a
smaller sanity-check DAG, e.g.:
    python generate_dag.py --events GW150914 --out job_sanity_check.dag
"""

import argparse

ALL_EVENTS = [
    "GW150914", "GW190412", "GW190521", "GW190828",
    "GW200129", "GW200224", "GW191109", "GW200225",
    "GW231028", "GW231226", "GW240104",
]  # GW191204 (Mc=8.57) and GW241110 (Mc=9.86) excluded -- out of prior range

TYPES = ["control", "dirty", "prediction"]

# Paths below are relative to job.sub's initialdir (scripts/pe/), not to
# this condor/ dir where job.dag itself lives.
INJECTION_FILE = "../../PE_results/simulated_separation_v1/pe_cases_n10.pkl"
SEED = "2026"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--events", type=str, default=None,
                         help="Comma-separated event subset (default: all 11 in-prior events)")
    parser.add_argument("--out", type=str, default="job.dag")
    args = parser.parse_args()

    events = args.events.split(",") if args.events else ALL_EVENTS
    unknown = set(events) - set(ALL_EVENTS)
    if unknown:
        raise SystemExit(f"Unknown event(s): {unknown} (or excluded as out-of-prior-range)")

    lines = ["# DAGMan workflow: simulated-case control/dirty/prediction PE sweep", ""]
    for event in events:
        for ptype in TYPES:
            job_name = f"{event}_{ptype}"
            outdir = f"../../PE_results/simulated_pe/{event}/{ptype}"
            lines.append(f"JOB {job_name} job.sub")
            lines.append(
                f'VARS {job_name} seed="{SEED}" label="{job_name}" type="{ptype}" '
                f'injection_label="{event}" injection_file="{INJECTION_FILE}" outdir="{outdir}"'
            )
            lines.append(f"RETRY {job_name} 2")
            lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    n = len(events) * len(TYPES)
    print(f"Wrote {args.out}: {n} jobs ({len(events)} events x {len(TYPES)} types)")


if __name__ == "__main__":
    main()
