"""Generate job.dag for the simulated-case control/dirty/prediction PE sweep.

Sweeps every event in pe_cases_n10.pkl (generated by evaluate_pe_cases.py)
against the three injection types run.py understands, except events whose
chirp mass falls outside run.py's hardcoded prior range (10-100 Msun) --
those hit an immediate exit() in setup_priors. Run from anywhere; it only
writes scripts/pe/condor/job.dag.
"""

EVENTS = [
    "GW150914", "GW190412", "GW190521", "GW190828",
    "GW200129", "GW200224", "GW191109", "GW200225",
    "GW231028", "GW231226", "GW240104",
]  # GW191204 (Mc=8.57) and GW241110 (Mc=9.86) excluded -- out of prior range

TYPES = ["control", "dirty", "prediction"]

# Paths below are relative to job.sub's initialdir (scripts/pe/), not to
# this condor/ dir where job.dag itself lives.
INJECTION_FILE = "../../PE_results/simulated_separation_v1/pe_cases_n10.pkl"
SEED = "2026"

OUT_PATH = "job.dag"


def main():
    lines = ["# DAGMan workflow: simulated-case control/dirty/prediction PE sweep", ""]
    for event in EVENTS:
        for ptype in TYPES:
            job_name = f"{event}_{ptype}"
            outdir = f"../../PE_results/simulated_pe/{event}/{ptype}"
            lines.append(f"JOB {job_name} job.sub")
            lines.append(
                f'VARS {job_name} seed="{SEED}" label="{job_name}" type="{ptype}" '
                f'injection_label="{event}" injection_file="{INJECTION_FILE}" outdir="{outdir}"'
            )
            lines.append(f"RETRY {job_name} 2")
            lines.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    n = len(EVENTS) * len(TYPES)
    print(f"Wrote {OUT_PATH}: {n} jobs ({len(EVENTS)} events x {len(TYPES)} types)")


if __name__ == "__main__":
    main()
