"""Generate job.dag for the simulated-case control/dirty/prediction PE sweep.

Sweeps every event in pe_cases_n10.pkl (generated by evaluate_pe_cases.py)
against the three injection types run.py understands, except events whose
chirp mass falls outside run.py's hardcoded prior range (10-100 Msun) --
those hit an immediate exit() in setup_priors. Run from anywhere; it only
writes scripts/pe/condor/job.dag by default; pass --events/--out for a
smaller sanity-check DAG, e.g.:
    python generate_dag.py --events GW150914 --out job_sanity_check.dag

job.sub runs each job in an execute-side sandbox (cluster.ldas.cit doesn't
NFS-mount /home) via HTCondor file transfer, so each job needs two distinct
references to the injection pickle: injection_file_src, a path resolvable
from job.sub's initialdir (scripts/pe/) at SUBMIT time, for staging it in;
and injection_file_name, just the basename, which is what run.py actually
sees once the file lands flat in the sandbox. outdir is likewise a flat,
job-unique directory name (no subdirectories) -- bilby creates it inside
the sandbox, and job.sub's transfer_output_files ships the whole thing
back on exit, landing in scripts/pe/<outdir>/ (job.sub's initialdir) once
the job completes.
"""

import argparse
from pathlib import Path

ALL_EVENTS = [
    "GW150914", "GW190412", "GW190521", "GW190828",
    "GW200129", "GW200224", "GW191109", "GW200225",
    "GW231028", "GW231226", "GW240104",
]  # GW191204 (Mc=8.57) and GW241110 (Mc=9.86) excluded -- out of prior range

TYPES = ["control", "dirty", "prediction"]

# Resolvable from job.sub's initialdir (scripts/pe/) at submit time.
INJECTION_FILE_SRC = "../../PE_results/simulated_separation_v1/pe_cases_n10.pkl"
INJECTION_FILE_NAME = Path(INJECTION_FILE_SRC).name
SEED = "2026"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--events", type=str, default=None,
                         help="Comma-separated event subset (default: all 11 in-prior events)")
    parser.add_argument("--out", type=str, default="job.dag")
    args = parser.parse_args()

    events = args.events.split(",") if args.events else ALL_EVENTS
    unknown = set(events) - set(ALL_EVENTS)
    if unknown:
        raise SystemExit(f"Unknown event(s): {unknown} (or excluded as out-of-prior-range)")

    lines = ["# DAGMan workflow: simulated-case control/dirty/prediction PE sweep", ""]
    for event in events:
        for ptype in TYPES:
            job_name = f"{event}_{ptype}"
            outdir = f"{job_name}_outdir"
            lines.append(f"JOB {job_name} job.sub")
            lines.append(
                f'VARS {job_name} seed="{SEED}" label="{job_name}" type="{ptype}" '
                f'injection_label="{event}" injection_file_src="{INJECTION_FILE_SRC}" '
                f'injection_file_name="{INJECTION_FILE_NAME}" outdir="{outdir}"'
            )
            lines.append(f"RETRY {job_name} 2")
            lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    n = len(events) * len(TYPES)
    print(f"Wrote {args.out}: {n} jobs ({len(events)} events x {len(TYPES)} types)")


if __name__ == "__main__":
    main()
